rhcos_url_prefix: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos
fcos_url_prefix: https://builds.coreos.fedoraproject.org/prod/streams/stable/builds

coreos_version_short: '{{ openshift_install_config.coreos_version | regex_replace("^([0-9]+\.[0-9]+)\.[0-9]+$", "\1") }}'

coreos_versions:
  ocp:
    installer_initramfs_url: '{{ rhcos_url_prefix }}/{{ coreos_version_short }}/{{ openshift_install_config.coreos_version }}/rhcos-{{ openshift_install_config.coreos_version }}-x86_64-installer-initramfs.x86_64.img'
    installer_kernel_url:    '{{ rhcos_url_prefix }}/{{ coreos_version_short }}/{{ openshift_install_config.coreos_version }}/rhcos-{{ openshift_install_config.coreos_version }}-x86_64-installer-kernel-x86_64'
    metal_bios_url:          '{{ rhcos_url_prefix }}/{{ coreos_version_short }}/{{ openshift_install_config.coreos_version }}/rhcos-{{ openshift_install_config.coreos_version }}-x86_64-metal.x86_64.raw.gz'
    openstack_qcow2_url:     '{{ rhcos_url_prefix }}/{{ coreos_version_short }}/{{ openshift_install_config.coreos_version }}/rhcos-{{ openshift_install_config.coreos_version }}-x86_64-openstack.x86_64.qcow2.gz'
    qemu_qcow2_url:          '{{ rhcos_url_prefix }}/{{ coreos_version_short }}/{{ openshift_install_config.coreos_version }}/rhcos-{{ openshift_install_config.coreos_version }}-x86_64-qemu.x86_64.qcow2.gz'
    vmware_ova_url:          '{{ rhcos_url_prefix }}/{{ coreos_version_short }}/{{ openshift_install_config.coreos_version }}/rhcos-{{ openshift_install_config.coreos_version }}-x86_64-vmware.x86_64.ova'
    checksum:                'sha256:{{ rhcos_url_prefix }}/{{ coreos_version_short }}/{{ openshift_install_config.coreos_version }}/sha256sum.txt'
  okd:
    installer_initramfs_url: '{{ fcos_url_prefix }}/{{ openshift_install_config.coreos_version }}/x86_64/fedora-coreos-{{ openshift_install_config.coreos_version }}-live-initramfs.x86_64.img'
    installer_kernel_url:    '{{ fcos_url_prefix }}/{{ openshift_install_config.coreos_version }}/x86_64/fedora-coreos-{{ openshift_install_config.coreos_version }}-live-kernel-x86_64'
    metal_bios_url:          '{{ fcos_url_prefix }}/{{ openshift_install_config.coreos_version }}/x86_64/fedora-coreos-{{ openshift_install_config.coreos_version }}-metal.x86_64.raw.xz'
    openstack_qcow2_url:     '{{ fcos_url_prefix }}/{{ openshift_install_config.coreos_version }}/x86_64/fedora-coreos-{{ openshift_install_config.coreos_version }}-openstack.x86_64.qcow2.xz'
    qemu_qcow2_url:          '{{ fcos_url_prefix }}/{{ openshift_install_config.coreos_version }}/x86_64/fedora-coreos-{{ openshift_install_config.coreos_version }}-qemu.x86_64.qcow2.xz'
    vmware_ova_url:          '{{ fcos_url_prefix }}/{{ openshift_install_config.coreos_version }}/x86_64/fedora-coreos-{{ openshift_install_config.coreos_version }}-vmware.x86_64.ova'
    checksum:                ''

coreos:
  installer_initramfs_url: '{{ coreos_versions[openshift_install_config.distribution].installer_initramfs_url }}'
  installer_kernel_url:    '{{ coreos_versions[openshift_install_config.distribution].installer_kernel_url }}'
  metal_bios_url:          '{{ coreos_versions[openshift_install_config.distribution].metal_bios_url }}'
  openstack_qcow2_url:     '{{ coreos_versions[openshift_install_config.distribution].openstack_qcow2_url }}'
  qemu_qcow2_url:          '{{ coreos_versions[openshift_install_config.distribution].qemu_qcow2_url }}'
  vmware_ova_url:          '{{ coreos_versions[openshift_install_config.distribution].vmware_ova_url }}'
  checksum:                '{{ coreos_versions[openshift_install_config.distribution].checksum }}'
